team-aliens/dms-front-admin

package.json, src/App.tsx, src/hooks/useToast.tsx, yarn.lock
=> (#7) merge: toastProvider, container, toast 커스텀훅 추가

src/apis/files/index.ts, src/apis/files/response.ts, src/apis/schools/index.ts, src/apis/schools/response.ts
=> (#10) merge: 학교 목록 불러오기 api, 파일 업로드 api 추가

package.json, src/App.tsx, src/apis/auth/request.ts, src/components/auth/Login.tsx, src/hooks/useErrorMessage.tsx, yarn.lock
=> (#12) merge: 로그인 리팩토링 및 로그인 로직 추가

src/apis/managers/index.ts, src/apis/managers/response.ts
=> (#17) merge: 2차 스프린트 api 정의

package.json, src/apis/managers/index.ts, src/apis/managers/response.ts, src/components/main/DetailBox/PointBox.tsx, src/components/main/DetailBox/StudentDetail.tsx, src/components/main/DetailBox/StudentInfo.tsx, src/components/main/Divider.tsx, src/components/main/StudentBox.tsx, src/components/main/StudentList.tsx, src/pages/main.tsx, src/router.tsx, yarn.lock
=> (#15) merge: 홈화면 퍼블리싱 및 기능 추가

package.json, src/components/WithNavigatorBar.tsx, src/components/notice/NoticeDetailSummary.tsx, src/components/notice/NoticeItem.tsx, src/components/notice/NoticeList.tsx, src/pages/Main.tsx, src/pages/notice/Detail.tsx, src/pages/notice/List.tsx, src/pages/notice/Write.tsx, src/router.tsx, yarn.lock
=> (#25) merge: 공지사항 부분 퍼블리싱

src/apis/notice/index.ts, src/apis/notice/request.ts, src/apis/notice/response.ts
=> (#27) merge: 3차 스프린트 api 정의

src/apis/auth/index.ts, src/apis/auth/response.ts, src/apis/managers/index.ts, src/apis/managers/response.ts, src/apis/schools/index.ts, src/apis/schools/request.ts, src/apis/schools/response.ts, src/apis/users/index.ts, src/apis/users/request.ts, src/components/modals/ChangeQnA.tsx, src/components/modals/LogOut.tsx, src/components/myPage/Confirmation.tsx, src/components/myPage/Verification.tsx, src/context/modal.tsx, src/hooks/useModal.tsx, src/index.tsx, src/pages/myPage/ChangePwd.tsx, src/pages/myPage/index.tsx, src/utils/queryKeys.ts
=> (#32) merge: 4차 스프린트 api 연결

src/apis/studyRooms/index.ts, src/apis/studyRooms/request.ts, src/apis/studyRooms/response.ts
- 기존에 api로직과 커스텀훅으로 따로 빼서 사용하던 방식을 합침
- resolved #46
=> merge: 자습실 api 설정(#46)

package.json, src/apis/studyRooms/index.ts, src/components/WithNavigatorBar.tsx, src/components/apply/SeatSetting.tsx, src/context/seatSetting.tsx, src/pages/apply/CreateRoom.tsx, yarn.lock
=> merge: 자습실 버그 수정

src/pages/notice/Detail.tsx
=> merge: 공지사항 줄바꿈 버그 수정

src/components/main/StudentList.tsx, src/components/modals/AddStudyRoomTime.tsx, src/components/modals/DeleteStudyRoomTime.tsx, src/context/modal.tsx, src/pages/apply/StudyRoomList.tsx
서버 없이 UI 퍼블리싱만 했습니다
- 
- resolved # 
close #58
=> feat: 자습실 시간 선택 UI 추가

src/apis/managers/response.ts, src/components/main/DetailBox/StudentInfo.tsx
- 
호실 타입을 number에서 string으로 변경하였습니다.
- resolved # 
resolved #62
=> fix: 호실 타입 number에서 string으로 변경

src/components/main/DetailBox/DetailBox.tsx, src/components/main/DetailBox/PointBox.tsx, src/components/main/DetailBox/StudentDetail.tsx, src/components/main/DetailBox/StudentInfo.tsx, src/components/main/StudentList.tsx, src/components/modals/DeleteStudent.tsx, src/hooks/useMangersApis.tsx, src/pages/Home.tsx
- 
학생 상세 확인 필터 추가
학생 삭제 추가
- resolved #67
=> (#67)merge: 학생 상세 확인 수정

src/apis/points/index.ts, src/components/main/DetailBox/PointItem.tsx, src/components/main/PointList.tsx, src/components/main/StudentList.tsx, src/components/modals/DeletePointOption.tsx, src/components/modals/GivePointOptionsModal.tsx, src/components/modals/ViewPointOptionsModal.tsx, src/pages/Home.tsx
- 
- 모달 크기 조절
- 상/벌점 항목 삭제 모달 수정
- resolved #82
=> 상/벌점 항목 삭제 모달 에러 수정 및 모달 크기 조절

src/components/modals/SchoolCheckingCode.tsx, src/components/modals/ViewPointOptionsModal.tsx, src/context/modal.tsx, src/pages/myPage/index.tsx
- 
학교 확인 코드 재발급 할 때 한 번 더 확인 할 수 있도록 재확인 모달 팝업
- resolved #86
=> (#86)merge: 학교 확인 코드 재발급 재확인 모달

src/apis/points/index.ts, src/components/MultiRangeSlider.tsx, src/components/modals/GivePointOptionsModal.tsx, src/components/modals/ViewPointOptionsModal.tsx
- 
- 상/벌점 필터 +인식 오류 수정
- 상/벌점 부여 모달 연속 부여 버그 수정
- resolved #92
=> (#92) merge: 상/벌점 필터 버그 및 상/벌점 부여 버그 수정

src/apis/points/index.ts, src/apis/remains/index.tsx, src/components/main/PointList.tsx, src/components/modals/AddSeatType.tsx, src/hooks/usePointsApi.tsx, src/hooks/useRemainApi.tsx, src/pages/Home.tsx, src/pages/apply/remains/index.tsx, src/utils/decoder.ts, src/utils/excel.ts
=> feat: 엑셀 파일 다운로드시 서버에서 보내주는 파일명 사용

src/apis/points/request.ts, src/apis/points/response.ts, src/components/main/DetailBox/PointItem.tsx, src/components/modals/GivePointOptionsModal.tsx, src/components/modals/ViewPointOptionsModal.tsx
기존에 일일이 관리하던 state를 useForm으로 관리하도록 수정
- 
- resolved #96
=> (#96) merge: 기존에 일일이 관리하던 state를 useForm으로 관리하도록 수정

src/apis/auth/index.ts, src/components/modals/LogOut.tsx, src/hooks/useAuthApi.tsx, src/pages/myPage/index.tsx, src/utils/setUseableFeatures.ts
=> feat: 토큰 재발급시에도 사용 가능한 기능 업데이트

src/apis/points/index.ts, src/components/main/DetailBox/PointItem.tsx, src/components/main/DetailBox/StudentDetailPoint.tsx, src/components/main/PointList.tsx, src/components/main/StudentList.tsx, src/components/modals/GivePointOptionsModal.tsx, src/components/modals/ViewPointOptionsModal.tsx
- 토스트 버그 수정
- 상/벌점 부여시 선택 항목 해제
- resolved #98
=> (#98) merge: 토스트 에러 수정 및 상/벌점 부여시 선택 항목 해제

src/App.tsx, src/index.tsx, src/pages/NotFound.tsx, src/router.tsx
=> feat: 404페이지
